CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    institution_id TEXT,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('student', 'admin')),
    reg_number TEXT,
    course TEXT,
    has_voted INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS elections (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'closed',
    is_active INTEGER NOT NULL DEFAULT 0,
    created_by INTEGER REFERENCES users (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS candidates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    election_id INTEGER NOT NULL REFERENCES elections (id),
    position TEXT NOT NULL,
    manifesto TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS votes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users (id),
    candidate_id INTEGER NOT NULL REFERENCES candidates (id),
    election_id INTEGER NOT NULL REFERENCES elections (id),
    position TEXT NOT NULL,
    voter_blind_hash TEXT NOT NULL,
    encrypted_vote TEXT NOT NULL,
    encrypted_key TEXT NOT NULL,
    vote_hash TEXT NOT NULL UNIQUE,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, election_id, position)
);

CREATE OR REPLACE FUNCTION prevent_vote_changes()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'Votes are append-only and cannot be modified';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS prevent_vote_update ON votes;
CREATE TRIGGER prevent_vote_update
BEFORE UPDATE ON votes
FOR EACH ROW
EXECUTE FUNCTION prevent_vote_changes();

DROP TRIGGER IF EXISTS prevent_vote_delete ON votes;
CREATE TRIGGER prevent_vote_delete
BEFORE DELETE ON votes
FOR EACH ROW
EXECUTE FUNCTION prevent_vote_changes();

CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    user_id INTEGER REFERENCES users (id),
    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    previous_hash TEXT NOT NULL,
    current_hash TEXT NOT NULL UNIQUE,
    merkle_root TEXT
);

CREATE TABLE IF NOT EXISTS merkle_roots (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    election_id INTEGER NOT NULL REFERENCES elections (id),
    merkle_root TEXT NOT NULL,
    computed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS otp_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users (id),
    otp_code TEXT NOT NULL,
    expiry_time TIMESTAMPTZ NOT NULL,
    is_used INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_candidates_election ON candidates (election_id);
CREATE INDEX IF NOT EXISTS idx_votes_election ON votes (election_id);
CREATE INDEX IF NOT EXISTS idx_votes_position ON votes (election_id, position);
CREATE INDEX IF NOT EXISTS idx_votes_blind_hash ON votes (voter_blind_hash);
CREATE INDEX IF NOT EXISTS idx_audit_logs_time ON audit_logs (timestamp);
CREATE INDEX IF NOT EXISTS idx_otp_sessions_user ON otp_sessions (user_id);
